#!/usr/bin/env python3
"""Generate disordered well configs for MBL sweep.

Takes a clean base config and adds quenched positional disorder to well
centers: center_i -> center_i + δ_i, where δ_i ~ N(0, σ²) in x and y.

Usage:
    python3 scripts/gen_disorder_configs.py --base configs/scaling/n8_grid_d6_s42.yaml \
        --sigma-list 0.0 0.3 0.6 1.0 1.5 2.0 3.0 --n-realizations 4

    python3 scripts/gen_disorder_configs.py --base configs/scaling/n8_grid_d6_s42.yaml \
        --sigma-list 1.0 --n-realizations 1 --dry-run
"""
from __future__ import annotations

import argparse
import copy
import random
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
OUT_BASE = REPO / "configs" / "mbl"


def add_disorder(cfg: dict, sigma: float, rng_seed: int) -> dict:
    rng = random.Random(rng_seed)
    cfg = copy.deepcopy(cfg)
    wells = cfg["system"]["wells"]
    for well in wells:
        center = list(well["center"])
        center[0] += rng.gauss(0.0, sigma)
        center[1] += rng.gauss(0.0, sigma)
        well["center"] = [round(c, 6) for c in center]
    return cfg


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", type=Path, required=True,
                        help="Clean base config YAML")
    parser.add_argument("--sigma-list", type=float, nargs="+",
                        default=[0.0, 0.3, 0.6, 1.0, 1.5, 2.0, 3.0],
                        help="Disorder strengths in units of ℓ_HO")
    parser.add_argument("--n-realizations", type=int, default=4,
                        help="Number of disorder realizations per sigma")
    parser.add_argument("--out-dir", type=Path, default=None)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    base_cfg = yaml.safe_load(args.base.read_text())
    base_stem = args.base.stem  # e.g. n8_grid_d6_s42

    out_dir = args.out_dir or (OUT_BASE / base_stem)
    out_dir.mkdir(parents=True, exist_ok=True)

    generated = []
    for sigma in args.sigma_list:
        sig_tag = f"sig{str(sigma).replace('.', 'p')}"
        for real_idx in range(args.n_realizations):
            rng_seed = hash((sigma, real_idx)) % (2**31)
            cfg = add_disorder(base_cfg, sigma, rng_seed)
            run_name = f"{base_stem}_mbl_{sig_tag}_r{real_idx}"
            cfg["run_name"] = run_name

            fname = f"{run_name}.yaml"
            out = out_dir / fname

            comment = (
                f"# MBL disorder sweep: σ={sigma} ℓ_HO, realization {real_idx}.\n"
                f"# Base: {args.base.name}, disorder seed={rng_seed}\n"
                f"# Generated by gen_disorder_configs.py\n"
            )
            yaml_str = comment + yaml.dump(cfg, default_flow_style=False, sort_keys=False)

            if args.dry_run:
                print(f"[DRY] {fname}  σ={sigma}, r={real_idx}")
            else:
                out.write_text(yaml_str)
                generated.append(out)
                print(f"Written: {fname}")

    if not args.dry_run:
        print(f"\nGenerated {len(generated)} configs in {out_dir}")


if __name__ == "__main__":
    main()
