#!/usr/bin/env python3
"""Generate magnetic spin-sector configs for B-sweep phase diagram.

Creates YAML config files for all requested (N, spin_sector, B) combinations
by patching the canonical B=0.5 configs with the new B value and run name.

Usage:
    # Generate B=0, 0.005, 0.01, 0.02, 0.05, 0.1 for N=3 all sectors
    python3 scripts/gen_magnetic_configs.py --N 3 --B-values 0.0 0.005 0.01 0.02 0.05 0.1

    # Generate B=0.005 for N=4 full ladder
    python3 scripts/gen_magnetic_configs.py --N 4 --B-values 0.005

    # Dry run (print but don't write)
    python3 scripts/gen_magnetic_configs.py --N 3 --B-values 0.005 0.01 --dry-run
"""

from __future__ import annotations

import argparse
import copy
import re
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
CFG_DIR = REPO / "configs" / "magnetic"

# Canonical spin sectors per N — source configs to use as templates
SECTOR_TEMPLATES: dict[int, list[tuple[int, int]]] = {
    3: [(0, 3), (1, 2), (2, 1), (3, 0)],
    4: [(0, 4), (1, 3), (2, 2), (3, 1), (4, 0)],
    2: [(0, 2), (1, 1), (2, 0)],
}

SOURCE_CONFIG_PATTERN = "n{N}_{n_up}up{n_down}down_b0p5_s42.yaml"


def _b_tag(B: float) -> str:
    """Convert 0.005 → 'b0p005', 0.5 → 'b0p50'."""
    s = f"{B:.3f}".replace(".", "p").rstrip("0").rstrip("p")
    if "p" not in s:
        s += "p0"
    return f"b{s}"


def _run_name(N: int, n_up: int, n_down: int, B: float) -> str:
    btag = _b_tag(B).replace("b", "b").replace("p", "p")
    return f"n{N}_mag_{n_up}up{n_down}down_{btag}_noref_s42"


def generate_config(
    N: int,
    n_up: int,
    n_down: int,
    B: float,
    source_cfg: dict,
) -> dict:
    cfg = copy.deepcopy(source_cfg)
    btag = _b_tag(B)
    cfg["run_name"] = _run_name(N, n_up, n_down, B)
    # Clear comments / existing E_ref
    sys = cfg.setdefault("system", {})
    sys["B_magnitude"] = round(B, 6)
    spin = cfg.setdefault("spin", {})
    spin["n_up"] = n_up
    spin["n_down"] = n_down
    # Remove CI-guided alpha / target energy
    training = cfg.setdefault("training", {})
    training["residual_target_energy"] = None
    training["alpha_start"] = 0.0
    training["alpha_end"] = 0.0
    # Wider sampler for noref
    training["sampler_sigma_tails"] = 1.00
    training["sampler_sigma_mixed_out"] = 0.70
    training["sampler_shell_radius"] = 1.20
    training["sampler_dimer_pairs"] = max(1, N - 1)
    return cfg


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--N", type=int, required=True, choices=[2, 3, 4],
                        help="Number of particles")
    parser.add_argument("--B-values", type=float, nargs="+", required=True,
                        help="Magnetic field values to generate configs for")
    parser.add_argument("--sectors", type=str, default=None,
                        help="Comma-separated 'nup_ndown' pairs, e.g. '1_2,2_1'. Default: all.")
    parser.add_argument("--out-dir", type=Path, default=CFG_DIR,
                        help="Output directory for YAML configs")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print filenames without writing")
    args = parser.parse_args(argv)

    N = args.N
    sectors = SECTOR_TEMPLATES[N]
    if args.sectors:
        sectors = []
        for pair in args.sectors.split(","):
            n_up_s, n_down_s = pair.strip().split("_")
            sectors.append((int(n_up_s), int(n_down_s)))

    args.out_dir.mkdir(parents=True, exist_ok=True)

    generated = []
    for B in args.B_values:
        if abs(B - 0.5) < 1e-6:
            print(f"  Skipping B=0.5 (canonical configs already exist)")
            continue
        for n_up, n_down in sectors:
            btag = _b_tag(B)
            out_name = f"n{N}_{n_up}up{n_down}down_{btag}_s42.yaml"
            out_path = args.out_dir / out_name

            # Find source template: prefer same sector at B=0.5, else closest sector
            src_name = SOURCE_CONFIG_PATTERN.format(N=N, n_up=n_up, n_down=n_down)
            src_path = CFG_DIR / src_name
            if not src_path.exists():
                # Fall back to 2up(N-2)down or any available
                fallback = sorted(CFG_DIR.glob(f"n{N}_*_b0p5_s42.yaml"))
                if not fallback:
                    print(f"  [skip] No template found for N={N}, using first available")
                    continue
                src_path = fallback[0]

            src_cfg = yaml.safe_load(src_path.read_text())
            new_cfg = generate_config(N, n_up, n_down, B, src_cfg)

            comment = (
                f"# N={N} magnetic: {n_up}↑{n_down}↓ spin sector, "
                f"B={B:.4g}, no CI ref (noref).\n"
                f"# Generated by gen_magnetic_configs.py\n"
            )
            yaml_str = comment + yaml.dump(new_cfg, default_flow_style=False, sort_keys=False)

            if args.dry_run:
                print(f"  [DRY] {out_path.name}  (N={N}, n_up={n_up}, n_down={n_down}, B={B})")
            else:
                out_path.write_text(yaml_str)
                generated.append(out_path)
                print(f"  Written: {out_path.name}")

    if not args.dry_run:
        print(f"\nGenerated {len(generated)} configs in {args.out_dir}")
        if generated:
            print("Ready to launch with:")
            print("  bash scripts/launch_magnetic_sector_sweep.sh  # (update GPU map as needed)")


if __name__ == "__main__":
    main()
